# msedgedriver.exe的路径
# ##### 修改为你的msedgedriver.exe的路径 #####
driver_path: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\edgedriver_win64\\msedgedriver.exe'

login_url: 'http://zhjw.scu.edu.cn/login'

username: '你的学号'      # 学号
password: '你的密码'      # 密码
course_id: '你的课程号'   # 课程号（写全，如：104169030_02） 

query_interval: 0.5 # (s) 抢课查询时间间隔

loading_sleep_time: 2 # (s) 等待网页加载的时间，网速慢的话可以适当调大
render_sleep_time: 1 # (s) 等待网页渲染的时间，网速慢的话可以适当调大
jumping_wait_time: 5 # (s) 最大等待跳转的时间，网速慢的话可以适当调大

bugfree: # 绝活，不用管
  bugfree_img_path: './utils/bugfree_img/' # bugfree图片路径 (相对路径，相对于工作目录)
  img_name: 'buddha.bugfree' # bugfree图片名称
  start_color: 'FF7EC7' # bugfree图片起始颜色
  end_color: 'FFED46' # bugfree图片结束颜色
